### ISSUE TITLE
commonjson.c:138:13: error: `FALSE' undeclared (first use in this function)

### ISSUE THREAD

**Issue by belongtothenight** [kgoldman/acs#2]
My building system and software details are listed below.

- Raspberry Pi 4 B
- [2023-05-03-raspios-bullseye-arm64.img.xz](http://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64.img.xz)
- [ibmacs1658.tar.gz](https://sourceforge.net/projects/ibmtpm20acs/files/ibmacs1658.tar.gz/download)
- Built as server
- Built for both TPM 1.2 & 2.0

Build command:

```bash
# Install Required Dependencies (some might not be listed, and MySQL is replaced with MariaDB)
sudo apt install -y libjson-c-dev apache2 PHP php-dev php-mysql mariadb-server libmariadb-dev libmariadb-dev-compat
# Ignore DB and Webpage setup
# Set Env Var
export CPATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
export LIBRARY_PATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
# Build server (clean previous build)
make -f makefiletpmc clean
make -f makefiletpmc
```

The following issue appears when using ```2023-05-03-raspios-bullseye-arm64.img.xz```, but not in ```Ubuntu 18.04.6 VM```.

```bash
commonjson.c: In function `JS_ObjectGetString`:
commonjson.c:138:13: error: `FALSE` undeclared (first use in this function)
  138 |  if (brc == FALSE) {
      |             ^~~~~
commonjson.c:138:13: note: each undeclared identifier is reported only once for each ...
commonjson.c:177:13: error: `FALSE` undeclared (first use in this function)
commonjson.c: In function `JS_ObjectGetStringNull`:
  177 |  if (brc == FALSE) {
      |             ^~~~~
make: *** [makefile-common:181: commonjson.o] Error 1
```

This issue can be solved with following commands:

```bash
# Add stdbool.h include
sed -i '39 i #include <stdbool.h>' "${path_ibmacs}/acs/commonjson.c"
# Replace FALSE with false
sed -i 's/FALSE/false/g' "${path_ibmacs}/acs/commonjson.c"
```

Hope this issue can help solving this issue.

**Comment by kgoldman** [comment]
Can you check the include tree? Did it complain about FALSE but not TRUE?

commonjson.c has #include "commonutils.h"

commonutils.h has

#ifndef FALSE
#define FALSE 0
#endif

(stdbool.h is probably everywhere now, but it wasn't when the project started.)

**Comment by belongtothenight** [comment]
Build with ```makefiletpmc```
FAILED: [ibmacs_1.log](https://github.com/kgoldman/acs/files/14433352/ibmacs_1.log)
```bash
# Install Required Dependencies (some might not be listed, and MySQL is replaced with MariaDB)
sudo apt install -y libjson-c-dev apache2 PHP php-dev php-mysql mariadb-server libmariadb-dev libmariadb-dev-compat
# Ignore DB and Webpage setup
# Set Env Var
export CPATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
export LIBRARY_PATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
# Build server (clean previous build)
make -f makefiletpmc
```

Build with ```makefiletpm12```
FAILED: [ibmacs_2.log](https://github.com/kgoldman/acs/files/14433365/ibmacs_2.log)
```bash
# Install Required Dependencies (some might not be listed, and MySQL is replaced with MariaDB)
sudo apt install -y libjson-c-dev apache2 PHP php-dev php-mysql mariadb-server libmariadb-dev libmariadb-dev-compat
# Ignore DB and Webpage setup
# Set Env Var
export CPATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
export LIBRARY_PATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
# Build server (clean previous build)
make -f makefiletpm12
```

Build with ```makefile```
FAILED: [ibmacs_3.log](https://github.com/kgoldman/acs/files/14433373/ibmacs_3.log)
```bash
# Install Required Dependencies (some might not be listed, and MySQL is replaced with MariaDB)
sudo apt install -y libjson-c-dev apache2 PHP php-dev php-mysql mariadb-server libmariadb-dev libmariadb-dev-compat
# Ignore DB and Webpage setup
# Set Env Var
export CPATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
export LIBRARY_PATH="${ibmtss_path}/utils:${ibmtss_path}/utils12"
# Build server (clean previous build)
make
```

> Can you check the include tree? Did it complain about FALSE but not TRUE?

Nope, it only reports about FALSE, somehow. I checked the ```commonutils.h```, and indeed TRUE is defined there and probably should error as well, but no.

**Comment by kgoldman** [comment]
I cannot reproduce this.
Please give the entire sequence, and try the latest code. Could you have some other code that defines FALSE?  What OS, [compiler?](url)

**Comment by belongtothenight** [comment]
I was using ibmacs1658.tar.gz from source forge. This version create this issue with following setup:
1. Debian 11 (bullseye) on Raspberry Pi
2. gcc 10.2.1-6

The latest code clone from your repo doesn't create this issue!
